---
- name: Demo VPC Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vpc_name: demo
    aws_region: us-east-1

    # vpc-stack.json
    vpc_cidr: 172.22.0.0/16
    subnets_cidrs: 172.22.0.0/24,172.22.1.0/24,172.22.2.0/24

  environment:
    AWS_DEFAULT_REGION: "{{aws_region}}"
  tasks:
    - name: Configure VPC and Subnets
      cloudformation:
        stack_name: "{{ vpc_name }}-vpc"
        state: present
        template: vpc-stack.json
        template_parameters:
          VpcCidr:  "{{ vpc_cidr }}"
          SubnetsCidrs: "{{ subnets_cidrs }}"
      register: stack

    - name: Extract VPC Stack outputs
      set_fact:
        outputs: "{{ { 'vpc': stack.stack_outputs } }}"

    - name: Create App Cluster
      cloudformation:
        stack_name: "{{ vpc_name }}-app"
        state: present
        template: app-stack.json
        template_parameters:
          VpcId: "{{ outputs.vpc.VpcId }}"
          AppSubnets: "{{ outputs.vpc.Subnets }}"
          AppImageId: "ami-6869aa05"
          AppInstanceType: t2.nano
          DnsZone: demo.e-it.nz.
          KeyName: michael.ludvig
          SshInCidr: 210.54.38.87/32
      register: stack

    - name: Extract VPC Stack outputs
      set_fact:
        outputs: "{{ outputs | combine({ 'app': stack.stack_outputs }) }}"

